#SUNDAY NOV 22 7am Eastern (use http://currentmillis.com/ to generate a time to the Sunday just passed)
#For example, this will have the first draw on the 29. #todo: set last draw time to current time on first use.
#debug: true
msg-prefix: "&a[&cSecretSanta&a]&6 "
first-last-draw: 1448193600000
interval: 604800000 #1 week (milliseconds)
gift-box-player: CruXXx #username of skin to use head
blacklist-materials:
- DIRT
- SAND

remind-time-on-login: true
gui-title: "Secret Santa: Choose a gift"
giftMax: 5